# Post new event to the db
http://localhost:8181
POST /events
{
    "name":"hondurasjsconf",
    "startdate": 768346784368,
    "enddate": 43988943,
    "duration": 120,
    "location": {
        "name": "hondconf",
        "address": "san pedro sula",
        "country": "honduras",
        "opentime": 10,
        "closetime": 15,
        "halls": [{
            "name": "lobby",
            "location": "principal building",
            "capacity" : 150
        }]
    }
}

# get all the events
http://localhost:8181
GET /events


